name: jom_malaysia
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  azlistview: ^0.1.2
  algolia: ^0.1.7
  # search client https://pub.dev/packages/algolia#-changelog-tab-
  cached_network_image: ^2.0.0
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  common_utils: ^1.1.3
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  cupertino_icons: ^0.1.3
  dio: ^3.0.9
  # https://pub.dev/packages/dio#-changelog-tab-
  # fancy_on_boarding: ^1.5.0
  # https://pub.dev/packages/fancy_on_boarding#-changelog-tab-
  flustars: 0.2.6+1
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  fluro: ^1.6.2
  # 路由框架 https://pub.dev/packages/fluro#-changelog-tab-
  #community-based, can upload file
  flutter_webview_plugin: ^0.3.10+2
  #  https://pub.dev/packages/flutter_webview_plugin#-changelog-tab-
  flutter_cupertino_localizations: ^1.0.1
  flutter_spinkit: ^4.1.2+1
  # used for loading web view https://pub.flutter-io.cn/packages/flutter_spinkit#-changelog-tab-
  # flutter_launcher_icons: ^0.7.4
  # used to generate app icon
  flutter_rating_bar: ^3.0.1+1
  # used to build rating bar
  flutter_swiper: ^1.1.6
  # Flutter 轮播图 https://github.com/best-flutter/flutter_swiper
  geolocator: ^5.3.1
  #used to detect user gps status and locate
  #https://pub.dev/packages/geolocator#-changelog-tab-
  google_fonts: ^0.3.10
  # https://pub.dev/packages/google_fonts#-changelog-tab-
  intl_utils: ^1.2.1
  #enable i10n https://pub.dev/packages/intl_utils#-changelog-tab-
  intro_slider: ^2.2.9
  # https://pub.dev/packages/intro_slider#-changelog-tab-
  json_serializable: ^3.3.0
  # https://pub.dev/packages/json_serializable#-changelog-tab-
  json_annotation: ^3.0.1
  logger: ^0.7.0+2
  lpinyin: ^1.0.9
  dio_http_cache: ^0.2.6
  #json parser library
  multi_image_picker: ^4.6.5+rc.1
  # https://pub.dev/packages/multi_image_picker#-changelog-tab-
  #  image_picker: 0.6.3+1
  oktoast: ^2.3.1+1
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  photo_view: ^0.9.2
  # https://pub.dev/packages/photo_view#-changelog-tab-:
  # permission_handler: ^4.4.0+hotfix.2
  # https://pub.dev/packages/permission_handler#-changelog-tab-
  provider: ^4.0.4
  # 状态管理 https://pub.dev/packages/provider#-changelog-tab-
  share: ^0.6.3+6
  #https://github.com/flutter/plugins/tree/master/packages/share:
  shared_preferences: ^0.5.6+3
  # https://pub.dev/packages/shared_preferences#-changelog-tab-
  shimmer: ^1.1.0
  # https://pub.dev/packages/shimmer#-changelog-tab-
  sprintf: ^4.0.2
  # 格式化String https://github.com/Naddiseo/dart-sprintf
  rxdart: ^0.22.5
  # https://github.com/ReactiveX/rxdart
  url_launcher: ^5.4.2
  # 启动URL的插件 https://github.com/flutter/plugins/tree/master/packages/url_launcher
  webview_flutter: ^0.3.19+9
  # WebView插件 https://pub.dev/packages/webview_flutter#-changelog-tab-
  # google_maps_flutter: ^0.5.21+15
  #maybe will sub with firebase share
  ####FIREBASE
  cloud_firestore: ^0.13.4+2
  # https://pub.dev/packages/cloud_firestore#-changelog-tab-
  firebase_core: ^0.4.4+3
  # https://pub.dev/packages/firebase_core#-changelog-tab-
  firebase_analytics: ^5.0.11
  firebase_auth: ^0.15.5+3
  # https://pub.dev/packages/firebase_auth#-changelog-tab-
  google_sign_in: ^4.3.0
  # https://pub.dev/packages/google_sign_in#-changelog-tab-
  ###firebase end
  # # 用于日历功能 https://github.com/apptreesoftware/date_utils
  # # date_utils: ^0.1.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
    # 集成测试
  flutter_driver:
    sdk: flutter
  # 单元测试
  build_runner: ^1.8.1
  #  https://pub.dev/packages/build_runner#-changelog-tab-

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Materialecause test >=1.12.0 depends on test_api 0.2.14 and every version of flutter_driver from sdk depends on test_api 0.2.11, test >=1.12.0 is incompatible with flutter_driver from sdk.can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/json/
    - assets/data/
    - assets/icons/
    - assets/images/
    - assets/images/place/
    - assets/images/place/2.0x/
    - assets/images/login/
    - assets/images/login/providers/
    - assets/images/login/providers/2.0x/
    - assets/images/login/providers/3.0x/
    - assets/images/explore/
    - assets/images/state/
    - assets/images/ads/
    - assets/images/account/
    - assets/images/overview/
    - assets/images/widgets/rating/
    - assets/images/explore/featured/
    - assets/images/comment/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
# flutter_icons:
#   image_path: assets/icons/JomN9.png
#   android: false
#   ios: false
flutter_intl:
  enabled: true
