name: jom_malaysia
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  # 状态管理 https://github.com/rrousselGit/provider
  provider: ^3.2.0

  # 网络库 https://github.com/flutterchina/dio
  dio: ^3.0.7
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^1.1.3
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: 0.2.6+1
  # Flutter 轮播图 https://github.com/best-flutter/flutter_swiper
  flutter_swiper: ^1.1.6
  # https://github.com/ReactiveX/rxdart
  rxdart: ^0.22.5
  # 启动URL的插件 https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher:
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^2.0.0-rc
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^2.2.1
  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^1.5.1
  # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: ^0.3.16
  # For future implementation
  flutter_localizations:
    sdk: flutter
  # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^4.0.2
  google_maps_flutter: ^0.5.21+15
  flutter_launcher_icons: ^0.7.4

  # 图片选择插件 https://github.com/flutter/plugins/tree/master/packages/image_picker
  # image_picker: 0.6.2+1
  # # 侧滑删除 https://github.com/letsar/flutter_slidable
  # flutter_slidable: ^0.5.4
  # # 列表悬浮头 https://github.com/fluttercommunity/flutter_sticky_headers
  # sticky_headers: ^0.1.8+1
  # # 城市选择列表 https://github.com/flutterchina/azlistview
  # azlistview: ^0.1.2
  # # 用于日历功能 https://github.com/apptreesoftware/date_utils
  # # date_utils: ^0.1.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
    # 集成测试
  flutter_driver:
    sdk: flutter
  # 单元测试
  test: ^1.6.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/data/
    - assets/images/
    - assets/images/home/
    - assets/images/store/
    - assets/images/state/
    - assets/images/order/
    - assets/images/order/dark/
    - assets/images/login/
    - assets/images/goods/
    - assets/images/shop/
    - assets/images/account/
    - assets/images/statistic/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  image_path: assets/icons/JomN9.png
  android: true
  ios: true