name: Flutter Unit Tests

on: [pull_request]

jobs:
  test:
    name: Linux Flutter Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
          KEY_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          run: echo $KEY_JKS > key.jks
      - run: flutter pub get
      # Run widget tests for our flutter project.
      - run: flutter test
